services:

    _defaults:
        autowire: true
        autoconfigure: true

    Tastaturberuf\AnyAccessBundle\Contao\DataContainer\PageDataContainer: ~
    Tastaturberuf\AnyAccessBundle\EventListener\GeneratePageListener: ~
    Tastaturberuf\AnyAccessBundle\Contao\Anyaccess: ~